### ISSUE TITLE
Keymaps: Empty layers cause a build error

### ISSUE THREAD

**Issue by musl** [zmkfirmware/zmk#803] opened 2021-05-20 04:02 UTC
If a layer contains nothing but phandles, the following build error occurs:

```
devicetree error: expected property 'bindings' in /keymap/layer_6 in nice_nano.dts.pre.tmp to be assigned with 'bindings = < &foo 1 2 ... &bar 3 4 ... >' (a mix of phandles and numbers), not 'bindings = < &none &none &none &none &none &none &none &none &none &none &none &none &none &none &none &none &none &none &none &none &trans &none &none &none &trans &none &none &none &none &none &none &none &none &none &none &trans &trans &trans &trans &trans &trans &trans >;'
```

Empty layers can be useful if you're not done planning all the layers and want to type on the board while you're figuring it out.

**Comment by joelspadin** [comment] 2021-05-20 06:36
Duplicate of #241

**Closed by joelspadin** 2021-05-20 06:36 UTC
Labels: duplicate
