### ISSUE TITLE
Combos with `slow-release` produce error during build

### ISSUE THREAD

**Issue by anuvyklack** [zmkfirmware/zmk#2304] opened 2024-05-12 14:57 UTC
If I add combo with `slow-release` option in my config file, I always get error during build.

The example of combo I'm trying to add:
```
/ {
    combos {
        compatible = "zmk,combos";
        f7_combo {
            timeout-ms = <500>;
            bindings = <&kp F7>;
            key-positions = <LM3 LM2 LM1>;
            layers = <FUNC>;
            slow-release = <true>;
        };
    };
};
```

**Comment by caksoylar** [comment] 2024-05-12 23:16
The syntax for boolean properties is `slow-release;`, see https://zmk.dev/docs/config#bool-1 for a reference.

**Comment by caksoylar** [comment] 2024-05-13 17:18
Closing as user error, comment again if there is trouble.

**Closed by caksoylar** 2024-05-13 17:18 UTC

**Comment by alfiedotwtf** [comment] 2024-10-02 01:05
I just bumped into this too - I think the problem is the datatype is bool and the docs say the default value is "false". Maybe the docs should be changed to this being a switch - either it exists or not.

**Comment by caksoylar** [comment] 2024-10-02 05:57
I understand the confusion, would be nice to reduce it somehow. The above linked section does document it, and given [Zephyr seems to call these booleans as well](https://docs.zephyrproject.org/3.5.0/build/dts/bindings-syntax.html#type), I wouldn't want to deviate from that in ZMK docs.
