### ISSUE TITLE
Cannot roll PLUS EQUAL

### ISSUE THREAD

**Issue by pujvz** [zmkfirmware/zmk#1766] opened 2023-04-20 18:54 UTC
I am unable to roll `PLUS` and `EQUAL`. 
- Expected output: `+=`
- Actual output: `+`

In order to achieve the desired output `+=`, `PLUS` must be released prior to pressing `EQUAL`. The same is true in reverse for `=+`.

This behavior also occurs when I try to roll `MINUS` and `UNDER`. I am aware that `KP_PLUS`, `KP_EQUAL`, `KP_MINUS` are a workaround, but this is not an option for me because the software I use for work incorrectly interprets these codes.

**Comment by caksoylar** [comment] 2023-04-20 20:10
This looks like a duplicate of #1076.

**Comment by pujvz** [comment] 2023-04-20 21:59
Thanks @caksoylar . Yes, this is a duplicate of #1076 . I did not find this issue when searching for the original issue.

**Closed** 2023-04-20 22:00 UTC
