### ISSUE TITLE
Warning: Node.js 16 actions are deprecated. 

### ISSUE THREAD

**Issue by kbirkenmayer** [zmkfirmware/zmk#2139] opened 2024-01-27 05:58 UTC
Hello all, I'm getting the following warning when I trigger a build:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: 
actions/upload-artifact@v3. For more information see: 
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

This looks like just a gentle reminder to migrate to node 20 on github actions, however I do not get it for all of my builds?
Regardless, my build worked just fine, just wanted to bring this up here in case creating visibility helps out.

**Comment by caksoylar** [comment] 2024-01-27 19:49
Thanks for reporting! We are aware of it and an attempt was made to fix it in #2136 and then reverted in #2137 due to backwards incompatible changes that broke the workflow. Looks like it should be possible to reproduce the old behavior with [an extra step](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#merging-multiple-artifacts), so it should be fixed soon.

**Closed** 2024-01-30 00:44 UTC
