### ISSUE TITLE
Apple "Globe key" modifier (Fn key)

### ISSUE THREAD

**Issue by dxmh** [zmkfirmware/zmk#947] opened 2021-09-21 08:50 UTC
Apple now use an additional modifier key: "Globe"

The Globe key can be seen in the bottom left of this [MacBook Air keyboard](https://support.apple.com/en-gb/guide/macbook-air/apdab672d5e9/mac):

![image](https://user-images.githubusercontent.com/60922914/134165296-d0543987-01fc-4761-b476-daffc4b3fc1f.png)

(The Globe key is now also standard on [iPad keyboards](https://support.apple.com/en-us/HT211091), and [Apple's new external keyboards](https://support.apple.com/en-gb/guide/imac/apd0e7983e19/mac) for other Macs.)

### The problem

It's not possible to send the Globe key with ZMK, but the Globe key is used heavily in recent versions of Apple operating systems. 

Here are some keyboard shortcuts in iPadOS 15 that use the Globe key:

> Go to Home Screen: Globe + H
> Show App Library: Shift + Globe + A
> Quick Note: Globe + Q
> Siri: Globe + S
> Control Center: Globe + C
> Notification Center: Globe + N
> App Switcher: Globe + Up Arrow
> Next App: Globe + Left Arrow
> Tile Window Left: Control (^) + Globe + Left Arrow
> Tile Window Right: Control (^) + Globe + Right Arrow
> Show Slide Over: Globe + Backslash \
> Move to Left Slide Over: Option (⌥) + Globe + Left Arrow
> Move to Right Slide Over: Option (⌥) + Globe + Right Arrow
> Source: https://www.imore.com/all-global-keyboard-shortcuts-ipad-ipados-15

I believe the Globe key is a repurpose/rebrand of Apple's own "Fn key" which has been around for a while. Apple's Fn key has its own keycode which is not usually available in custom keyboard firmware:

> Unlike most Fn keys, the one on Apple keyboards actually has its own keycode... sort of. It takes the place of the sixth keycode in a basic 6KRO HID report -- so an Apple keyboard is in fact only 5KRO. 

More information about the Apple Fn key can be found at https://beta.docs.qmk.fm/faqs/faq_keymap#fn-key-on-macos.

### Workaround

Previously, when this key was purely `Fn`, it was possible to work around the inability to send `Fn`+`8` for "Play/Pause" by instead sending the desired `C_PLAY_PAUSE`. However, these kinds of workarounds do not apply to Globe as there's no keycode for the desired result (e.g. "Tile Window Left").

Fortunately, Apple provides the ability to remap modifiers at the Operating System level on all their devices - it is possible for ZMK to send Caps Lock (`&kp CAPS`) and for the Apple OS to treat it as the Globe key. 

![7345B536-051C-41E1-AC9D-098F4B8A349E](https://user-images.githubusercontent.com/60922914/134216193-a3751184-a353-48b1-ae88-675edccfae83.jpeg)

Note that on an iOS/iPadOS device, accessing this settings pane can be troublesome (but not impossible) as discussed in #378.

**Comment by minjaep** [comment] 2021-09-25 15:01
So it is not an 'issue' as Apple wants to make it a propriety key (maybe you need a license to implement it, as it seems like OS checks if the keyboard supports globe or not). I also have no problem using capslock instead of globe.

**Comment by dxmh** [comment] 2021-11-13 08:21
> I also have no problem using caps lock instead of globe.

I find the main problem with this approach is the inability to use capslock in [modifier functions](https://zmk.dev/docs/codes/modifiers/#modifier-functions) in the keymap. 

For example: `&kp LC(A)` in the keymap sends `LEFT_CONTROL`+`A`, but I don’t believe it’s possible to do the equivalent for `CAPSLOCK`+`A` (`GLOBE`+`A`).

**Comment by daaaaaaaaaniel** [comment] 2022-03-16 00:22
In QMK, there's a patch that enables the Apple fn <img src="https://help.apple.com/assets/61D4C1B5425F2576373C512A/61D4C1B7425F2576373C5132/en_US/1faa76ae5882af1040a984bf04c1f6ce.png" alt="the Globe key" originalimagename="SharedGlobalArt/IL_Globe.png" width="17" height="17"> key. <https://gist.github.com/fauxpark/010dcf5d6377c3a71ac98ce37414c6c4>. How far off are we from being able to do the same sort of thing in ZMK?

**Comment by petejohanson** [comment] 2022-03-16 00:44
I am in full agreement with the QMK devs, we won't ever imitate a company's VID to enable a feature.

We would need to petition Apple to somehow add the VID we use to their allowed list, before bothering enhancing ZMK's HID layer to support this.

**Comment by eytanhanig** [comment] 2022-09-23 05:20
> we won't ever imitate a company's VID to enable a feature

They're over 15% of the market. Is there any legal reason we can't support this? It'd be unfortunate to punish users just because the OS vendor doesn't play well with others.

**Comment by Hello9999901** [comment] 2022-09-23 12:33
You can work around this by binding an unused key and remapping using `hidutil` on macOS. You can't do this on iPadOS, however.

**Comment by petejohanson** [comment] 2022-09-24 15:09
> > we won't ever imitate a company's VID to enable a feature
> 
> They're over 15% of the market. Is there any legal reason we can't support this? It'd be unfortunate to punish users just because the OS vendor doesn't play well with others.

Users are welcome to override the VID and PID for their local builds. The project itself won't ever do this by default, that would open us up to lawsuits from Apple or the USB-IF, in theory. 

The better way is to petition Apple to add our IDs, or change their software.

**Comment by spencerthayer** [comment] 2023-02-05 20:04
How does Keychron get away with this?

**Comment by tinydogio-joshua** [comment] 2023-02-15 13:45
> How does Keychron get away with this?

Seems to be fn2 on all my Keychron devices.

**Comment by mtskf** [comment] 2023-03-24 05:43
Not yet sorted?

**Comment by or-agami** [comment] 2023-05-28 15:27
> I find the main problem with this workaround is the inability to use capslock in [modifier functions](https://zmk.dev/docs/codes/modifiers/#modifier-functions) in the keymap.
> 
> For example: `&kp LC(A)` in the keymap sends `LEFT_CONTROL`+`A`, but I don’t believe it’s possible to do the equivalent for `CAPSLOCK`+`A` (`GLOBE`+`A`).

There is a workaround for using capslock in modifier functions?

**Comment by marzelwidmer** [comment] 2023-07-30 16:59
I facing the same issues...my workaround to use F1 etc. (my default are on my MacBooks F1 with FN key) to switch it on the OS

macOS Ventura
Choose Apple menu  > System Settings.
Click Keyboard in the sidebar.
Click the Keyboard Shortcuts button on the right.
Click Function Keys in the sidebar.
Turn on “Use F1, F2, etc. keys as standard function keys”.

**Comment by LandonSchropp** [comment] 2023-08-04 19:31
I'm using a workaround as well, but I wish we could support the globe character so that I could set consistent keyboard shortcuts between my laptop's keyboard and my Desktop keyboard.

**Comment by Hello9999901** [comment] 2023-08-04 21:47
Hey all, as Pete stated a year ago – "The project itself won't ever do this by default, that would open us up to lawsuits from Apple or the USB-IF, in theory."
Keychron shows up as an Apple keyboard (at least with `lsusb`), so I'm assuming they have some deal with Apple itself. Unfortunately, the tldr is that the Globe key will not be supported anytime soon (or ever). There are a variety of workarounds. My workaround uses `hidutil` and a little ways up the thread.
Just wanted to conclude some points of the discussion so far.

**Comment by ldebritto** [comment] 2023-09-13 13:49
> > I find the main problem with this workaround is the inability to use capslock in [modifier functions](https://zmk.dev/docs/codes/modifiers/#modifier-functions) in the keymap.
> > For example: `&kp LC(A)` in the keymap sends `LEFT_CONTROL`+`A`, but I don’t believe it’s possible to do the equivalent for `CAPSLOCK`+`A` (`GLOBE`+`A`).
> 
> There is a workaround for using capslock in modifier functions?

One could use a macro for that:
```
  caps_a: caps_a {
            label = "CAPS+A";
            compatible = "zmk,behavior-macro";
            wait-ms = <0>;
            tap-ms = <0>;
            #binding-cells = <0>;
            bindings
                = <&macro_press &kp CAPS>
                , <&macro_tap &kp A>
                , <&macro_release &kp CAPS>
                ;
        };
```

**Comment by eytanhanig** [comment] 2023-09-14 04:34
> The better way is to petition Apple to add our IDs, or change their software.

@petejohanson What are the next steps for starting this petition?

**Comment by petejohanson** [comment] 2023-09-14 04:41
> > The better way is to petition Apple to add our IDs, or change their software.
> 
> @petejohanson What are the next steps for starting this petition?

1. Figure out how best to contact Apple,
1. Write up the petition, including a link to this issue,
1. Send it to Apple.

This issue is definitely not high on my list of priorities, so whoever is motivated to do the above is welcome to.

**Comment by ReFil** [comment] 2023-09-20 18:48
I've successfully made globe key work on a zmk powered board. It doesn't use the fn key approach in that QMK patch, and doesn't require any changing of the VID/PID, it is simply a rarely used consumer keycode.
![image-16.png](https://github.com/zmkfirmware/zmk/assets/31960031/500285b8-d2cc-4a59-8bc3-6b9384604f1f)

**Comment by orand** [comment] 2023-09-20 20:16
Really? Are you the first person in the world to figure this out? If so, could you please elaborate? If not, where did you find how to do this?

**Comment by ldebritto** [comment] 2023-09-20 21:03
> I've successfully made globe key work on a zmk powered board. It doesn't use the fn key approach in that QMK patch, and doesn't require any changing of the VID/PID, it is simply a rarely used consumer keycode. ![image-16.png](https://user-images.githubusercontent.com/31960031/269387527-500285b8-d2cc-4a59-8bc3-6b9384604f1f.png)

So you’re using this key code? `C_AL_KEYBOARD_LAYOUT`? Or have you created a new one to post this Usage ID?

**Comment by ReFil** [comment] 2023-09-20 23:09
It's the 0x29D usage ID, I just added it to keys.h. it is specified in the apple accessory device specifications. There is no mention of the Fn key in said specification. It either uses the same code as the globe key or a proprietary method apple don't publish

**Comment by arabshapt** [comment] 2023-09-20 23:17
I just added that like and then used it in my config. the key did not register in karabiner eventviewer

**Comment by ReFil** [comment] 2023-09-20 23:43
Did you enable CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_FULL=y in adv360_left_defconfig

**Comment by ldebritto** [comment] 2023-09-21 00:17
While it still does not register in Karabiner Event Viewer as `fn`, it does work with my keymap after also changing my `.conf` to include the `CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_FULL=y` line.

Should anyone want to reproduce, follow these steps:

1. Edit your `.conf` file in the config folder to include the following line

```
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_FULL=y
```

2. Create a file in your config folder with the key definition. I've created the `apple_globe.h` file in my keymap folder with this single `#define` command:

```
/* Apple Globe key */
#define C_KEYBOARD_LAYOUT_SELECT (ZMK_HID_USAGE(HID_USAGE_CONSUMER, 0x029D))
#define GLOBE C_KEYBOARD_LAYOUT_SELECT
// As per PR 1938
```

3. Add the GLOBE key code to your keymap (mine is a &mt in the Z key)

```
&mt GLOBE Z
```

However it only seems to work if I have the keyboard connected via cable. When I use the keyboard connected via bluetooth, it just doesn't work.

So I guess there's still something else to change in keyboard settings. 

Still, many thanks for that, @ReFil ! I guess that we're getting closer to a solution.

**Comment by arabshapt** [comment] 2023-09-21 00:32
> Did you enable CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_FULL=y in adv360_left_defconfig
I tried with CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_FULL=y , still it did not work. It does not get registered... with wire or bluetooth

**Comment by arabshapt** [comment] 2023-09-21 06:17
Yes, it is enabled... I can try disabling it

**Comment by arabshapt** [comment] 2023-09-21 06:20
disabling it did not help

**Comment by ReFil** [comment] 2023-09-21 08:53
> While it still does not register in Karabiner Event Viewer as `fn`, it does work with my keymap after also changing my `.conf` to include the `CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_FULL=y` line.
> 
> Should anyone want to reproduce, follow these steps:
> 
> 1. Edit your `.conf` file in the config folder to include the following line
> 
> ```
> CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_FULL=y
> ```
> 
> 2. Create a file in your config folder with the key definition. I've created the `apple_globe.h` file in my keymap folder with this single `#define` command:
> 
> ```
> /* Apple Globe key */
> #define C_KEYBOARD_LAYOUT_SELECT (ZMK_HID_USAGE(HID_USAGE_CONSUMER, 0x029D))
> #define GLOBE C_KEYBOARD_LAYOUT_SELECT
> // As per PR 1938
> ```
> 
> 3. Add the GLOBE key code to your keymap (mine is a &mt in the Z key)
> 
> ```
> &mt GLOBE Z
> ```
> 
> However it only seems to work if I have the keyboard connected via cable. When I use the keyboard connected via bluetooth, it just doesn't work.
> 
> So I guess there's still something else to change in keyboard settings.
> 
> Still, many thanks for that, @ReFil ! I guess that we're getting closer to a solution.

If you use webhid explorer on a chromium based browser can you see the keycode working over bluetooth? https://nondebug.github.io/webhid-explorer/

Apologies for my relative lack of testing, I dont have a mac personally and have to borrow one for short periods of time to test it

**Comment by arabshapt** [comment] 2023-09-21 09:37
I hope we manage to make it work. Isn't globe or fn the same on mac? I would assume the difference is in hold and tap. 
How does adding apple_globe.h help at all? where do you reference that file? I added that line in ZMK repo(not zmk config)...
Do you have any idea whether one could add more modifiers that OS would understand? I am already using left and right modifiers as different modifiers. I think globe/fn could be used for than(in karabiner elements). But is there any way to also use something else as modifier?

**Comment by ReFil** [comment] 2023-09-21 13:18
I suspect this will not be compatible with NKRO in the same way that F13-F24 are not compatible with NKRO

**Comment by caksoylar** [comment] 2023-09-22 06:43
> However it only seems to work if I have the keyboard connected via cable. When I use the keyboard connected via bluetooth, it just doesn't work.

Note that changes like enabling NKRO or changing the consumer usage page size requires refreshing the HID report descriptor. For Windows, it seems to require the procedure described here: https://zmk.dev/docs/features/bluetooth#windows-connected-but-not-working. It is likely that macOS too will at least require a re-pair, if not a similar procedure.

**Comment by ldebritto** [comment] 2023-09-24 01:29
Following @caksoylar tip, I've fully reflashed my keyboard (both halves) and re-paired with my MacBook, now it works fine even via Bluetooth.

Karabiner Event Viewer does not recognize it as a keystroke, but other apps and the OS itself does. iPadOS as well.

Also, reporting back to @ReFil, this is the value from the HID Explorer on a Chromium Browser:
```
02 9D 02 00 00 00 00 00 00 00 00 00 00
```

**Comment by arabshapt** [comment] 2023-09-24 07:28
So did you have to turn off NKRO for it to work? Where do you use(import) apple_globe.h? Or is just creating it enough? Could you create a rule in Karabiner and check whether it can be used there even though karabinerviewer is not showing it?

**Comment by arabshapt** [comment] 2023-09-24 07:35
Does anybody know the technical reason why f13-24 do not work with NKRO anabled?

**Comment by ldebritto** [comment] 2023-09-24 11:01
@arabshapt , have a look at my repo. There you'll find all these answers. [ldebritto/zmk-config](https://github.com/ldebritto/zmk-config/tree/main/config)

**Comment by ReFil** [comment] 2023-09-24 11:27
Does it function as the Fn key as well as the globe key? I wasn't sure if apple handled the fn part of that key in a different way to the globe as it were as there's no mention of fn in the apple specification

**Comment by ldebritto** [comment] 2023-09-24 11:46
Actually, in Apple keyboards, `fn` and `globe` are physically the same. Recent keyboards use the globe in the keycap.

I’m not sure if this change is only cosmetical or if behind the key there is a different key code. For what is worth, in a world that many people would have mechanical keyboard, some of them would be very disappointed to realiza that their keyboard's fn key does not produce the behavior they expect when getting an Apple computer. Maybe that's the reason, but now I'm conjecturing.

In my testings, I have used a Magic Keyboard with the fn key and the my MacBook’s own keyboard (with the globe logo key). They map the same in Karabiner Event Viewer.

So I guess that even if they have different key codes, they map to the same outputs in the OS.

**Comment by danieleavitabile** [comment] 2023-10-02 00:43
I am relatively new in ZMK, and I would very much benefit from the Globe Key. Do I understand correctly from https://github.com/zmkfirmware/zmk/pull/1938 that we may have soon (or perhaps already have) a keycde now? If so, is it in a ZMK version that is still to be made public?

**Comment by caksoylar** [comment] 2023-10-02 00:49
@danieleavitabile Yes, if you build with an up-to-date version of ZMK (which is the default behavior if you followed the [user guide](https://zmk.dev/docs/user-setup)) then you should be able to use the `GLOBE` keycode that was added in that change.

**Comment by caksoylar** [comment] 2023-10-02 00:50
Closing since #1938 presumably fixes this, if anyone has issues with the keycode you can add a comment on this issue.

**Closed by caksoylar** 2023-10-02 00:50 UTC

**Comment by danieleavitabile** [comment] 2023-10-02 01:00
Thanks, if I understand correctly, I can just use the GLOBE code if I use GitHub actions for building the firmware

**Comment by caksoylar** [comment] 2023-10-02 01:06
Yes, unless you changed `config/west.yml` file, it will always build using the latest version of ZMK.

**Comment by LeonB** [comment] 2023-10-02 08:49
@ReFil very cool! Will this also be added to the Adv360 repo?

**Comment by arabshapt** [comment] 2023-10-02 13:48
On Ipad the globe gets registered, but on mac it does nothing for me... When I disable "modify events" in karabiner for my external keyboard(kinesis 360) then I see in unknown events in karabiner something(see image). The actual fn-key on my mac gets registered as 
  ```
  {
    "type": "up",
    "name": {"apple_vendor_top_case_key_code":"keyboard_fn"},
    "usagePage": "255 (0x00ff)",
    "usage": "3 (0x0003)",
    "misc": ""
  },
  ```
  using 0x0003 instead of 029d did not help...
![image](https://github.com/zmkfirmware/zmk/assets/26434809/678316ee-861d-4b7d-a6b1-205ad4f53521)

**Comment by ReFil** [comment] 2023-10-02 13:50
What version of macOS are you using? It seems that your fn key is using the older custom usage page method

**Comment by ReFil** [comment] 2023-10-02 13:57
That's odd, is the hardware recent too? I was able to get it to bring up the emoji screen on an m1 macbook pro which was the same thing the globe key on the integrated keyboard did. If your hardware is older it might explain it

**Comment by arabshapt** [comment] 2023-10-02 13:58
m2 macbook. Does the following help?
![Uploading image.png…]()

**Comment by arabshapt** [comment] 2023-10-02 13:59
<img width="830" alt="image" src="https://github.com/zmkfirmware/zmk/assets/26434809/116187a7-130d-43b9-a46b-61fbf5f68d13">

**Comment by arabshapt** [comment] 2023-10-02 14:00
> That's odd, is the hardware recent too? I was able to get it to bring up the emoji screen on an m1 macbook pro which was the same thing the globe key on the integrated keyboard did. If your hardware is older it might explain it

that makes me hopeful

**Comment by ReFil** [comment] 2023-10-02 14:06
Is it doing anything in the OS? as per [this comment](https://github.com/zmkfirmware/zmk/issues/947#issuecomment-1732450416) karabiner might not be able to detect it. Bear in mind it's possible the key is disabled in the  [MacOS keyboard settings](https://support.apple.com/my-mm/guide/mac-help/kbdm162/mac)

**Comment by arabshapt** [comment] 2023-10-02 14:11
my normal built in keyboard opens emoji panel, but kinesis does not open anything. On my second mac(macbook 16 2019) the fn keycode is the same 
```
{
  "type": "up",
  "name": {"apple_vendor_top_case_key_code":"keyboard_fn"},
  "usagePage": "255 (0x00ff)",
  "usage": "3 (0x0003)",
  "misc": ""
},
```

**Comment by arabshapt** [comment] 2023-10-02 14:12
is replacing 0x029d with 0x00ff enough? how can I add this myself to test whether it works?

**Comment by ReFil** [comment] 2023-10-02 14:16
Implementing the dedicated usage apple fn key is not trivial, are you trying this over USB or bluetooth?

**Comment by arabshapt** [comment] 2023-10-02 14:18
both. I could do the same thing you did in your PR or do you mean even more work than that?

**Comment by ReFil** [comment] 2023-10-02 14:20
It would be a lot more work to implement, where's your config repo? I can have a look to ensure the keyboard is correctly configured?

**Comment by arabshapt** [comment] 2023-10-02 14:24
here it is: https://github.com/arabshapt/Adv360-Pro-ZMK/tree/v3.0/config

**Comment by ReFil** [comment] 2023-10-02 14:26
at first glance this line shouldn't be there, if you're using full consumer usage it supercedes basic https://github.com/arabshapt/Adv360-Pro-ZMK/blob/1f5cc43ae89a16c9079f128913104f81f2520c9a/config/boards/arm/adv360/adv360_left_defconfig#L64C27-L64C27

**Comment by arabshapt** [comment] 2023-10-02 14:41
thank you, I commented it out)

**Comment by ReFil** [comment] 2023-10-03 10:07
It seems like the GLOBE keycode does not provide the full functionality of the globe/fn keys present on official apple keyboards, but does provide some of the functionality, With this in mind it might be worth reopening the issue or opening a new issue specifically about the Fn functionality

**Comment by ickc** [comment] 2023-10-24 20:20
I can confirm that the GLOBE keycode here is more limited than actual GLOBE key from Apple. I tried it on iPad Pro 12.9" 6th gen model with iPadOS 17.0.3, and it is working as expected (e.g. GLOBE key changes input sources.) But on the Macbook Pro 16" 2021 model with macOS Sonoma 14.0 (23A344), the GLOBE has no effects (e.g. it does not change input sources.)

Remapping in System Preferences > Keyboard > Keyboard Shortcuts... > Modifer Keys > Caps Lock to Globe gives full Globe/Fn functionality instead.

Also, in order to use the GLOBE keycode on Advantage 360, you need to follow https://github.com/zmkfirmware/zmk/issues/947#issuecomment-1743121985 and set `CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=n`. I don't think it is documented yet in the Adv360 repo.

**Comment by r4zendev** [comment] 2023-11-26 21:57
Facing this problem on Monterey 12.5, Air m2 2023, Glove80, configuring via their online tool. Any suggestions? The key seems totally unresponsive, even fn+bksp does not work. Combinations like fn+c, fn+e obviously don't work as well.

**Comment by ReFil** [comment] 2023-11-26 21:59
The keycode only works for the globe function, not the fn function of the key

**Comment by r4zendev** [comment] 2023-11-26 22:08
@ReFil FWIW globe function does not work for me as well. It does not toggle the languages either.
Are there any currently available solutions for the fn key though? That's what I'm looking for primarily.
