### ISSUE TITLE
Document how to setup a dongle

### ISSUE THREAD

**Issue by binduwavell** [zmkfirmware/zmk#2373] opened 2024-07-14 22:58 UTC
In particular, it appears that the need to set `CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2` on the central so that both halves may connect does not appear to be documented. It would be great if all of the steps required to setup a dongle could have a docs page. Was not horribly hard looking at other people's config but was a bit frustrating to have to do that and not follow official docs.

**Comment by caksoylar** [comment] 2024-07-14 23:11
Duplicate of #2044 in general, but documenting that specific config would be considered a docs bug fix.

**Closed** 2024-08-02 16:57 UTC
